### ISSUE TITLE
Call remote debug with a single statement

### ISSUE THREAD

**Issue by gmag11** [JoaoLopesF/RemoteDebug#18]
Using `if ( Debug.isActive( .. ) ) ` is a bit annoying if you have lots of debug messages.

Using a function like 
``` Arduino
Debug.printf( debugLevel , "Some string with some format place holders %d %s", some, variables );
```
code would be cleaner.

it could be implemented as
``` Arduino
size_t RemoteDebug::printf (uint8_t debugLevel, const char* format , ...) {
    if (isActive (debugLevel)) {
        va_list argptr;
        va_start (argptr, format);
        printf (format, argptr);
        va_end (argptr);
    } 
}
```
Do you agree?

**Comment by JoaoLopesF** [comment]
Hi, is a good suggestion. I make any tests with it and publish it soon

Thanks a lot

Joao

**Comment by JoaoLopesF** [comment]
Hi

I have now released a new version with something similar to your idea.

The RemoteDebug should be with isActive because this has a smaller overhead.

But now we have shortcuts:

DEBUG ("This is any any (always showed) - var% d \ n", var);
DEBUG_V ("This is a message of debug level VERBOSE \ n");
DEBUG_D ("This is a message of debug level DEBUG \ n");
DEBUG_I ("This is a message of debug level INFO \ n");
DEBUG_W ("This is a message of debug level WARNING \ n");
DEBUG_E ("This is a message of debug level ERROR \ n");

I hope you enjoy

thankful
Joao
