### ISSUE TITLE
Feature request: password

### ISSUE THREAD

**Issue by jeroenst** [JoaoLopesF/RemoteDebug#27]
Although it can be sniffed by wireshark, a password before entering the debug telnet connection would be nice to prevent unwanted users to open the debug console. The chance that it will be sniffed is pretty low on home lan environments.

**Comment by JoaoLopesF** [comment]
I agree. this already stay in my wish list
Thanks

**Comment by JoaoLopesF** [comment]
Hi @jeroenst 

I researched and found that telnet use advanced authentication (kerberos, etc.)
For production, telnet must have considerable encryption, kerkeros, etc.

Such as RemoteDebug now is not for production releases, 
this kind of authentication will not be done now.

I just commit a new version (1.4.0) with a simple password text request.

Because RemoteDebug is now for development environments only,
This is what I can do now.

Regards

Joao Lopes
